[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "warn"
perf = "warn"
complexity = "warn"

[workspace]
members = ["macros", "."]

[dependencies]
rlox-macros = { path = "macros"}

[dev-dependencies]
assert_cmd = "2.0"

